# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'robot_gui.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        MainWindow.setStyleSheet("QPushButton {\n"
"    background: qlineargradient(\n"
"        spread:pad, x1:0, y1:0, x2:1, y2:1, \n"
"        stop:0 #ff9a9e, stop:1 #fad0c4\n"
"    );\n"
"    color: white;\n"
"    border: none;\n"
"    padding: 12px 24px;\n"
"    font-size: 16px;\n"
"    font-weight: bold;\n"
"    border-radius: 8px;\n"
"    transition: all 0.3s ease-in-out;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background: qlineargradient(\n"
"        spread:pad, x1:0, y1:0, x2:1, y2:1, \n"
"        stop:0 #fad0c4, stop:1 #ff9a9e\n"
"    );\n"
"    transform: translateY(-3px);\n"
"    box-shadow: 0px 5px 15px rgba(0, 0, 0, 0.2);\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    transform: translateY(2px);\n"
"    box-shadow: 0px 2px 8px rgba(0, 0, 0, 0.15);\n"
"}\n"
"")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.stackedWidget = QtWidgets.QStackedWidget(self.centralwidget)
        self.stackedWidget.setGeometry(QtCore.QRect(30, 20, 741, 501))
        self.stackedWidget.setStyleSheet("")
        self.stackedWidget.setObjectName("stackedWidget")
        self.Home = QtWidgets.QWidget()
        self.Home.setStyleSheet("background: qlineargradient(\n"
"    spread:pad, x1:0, y1:0, x2:1, y2:1, \n"
"    stop:0 #ff7eb3, stop:1 #ff758c\n"
");\n"
"color: #3A3A3A;\n"
"")
        self.Home.setObjectName("Home")
        self.btn_crowdnav = QtWidgets.QPushButton(self.Home)
        self.btn_crowdnav.setGeometry(QtCore.QRect(200, 440, 141, 31))
        self.btn_crowdnav.setStyleSheet("background-color: red;")
        self.btn_crowdnav.setObjectName("btn_crowdnav")
        self.btn_muiltinav = QtWidgets.QPushButton(self.Home)
        self.btn_muiltinav.setGeometry(QtCore.QRect(360, 440, 171, 31))
        self.btn_muiltinav.setStyleSheet("background-color: red;")
        self.btn_muiltinav.setObjectName("btn_muiltinav")
        self.btn_arm = QtWidgets.QPushButton(self.Home)
        self.btn_arm.setGeometry(QtCore.QRect(550, 440, 141, 31))
        self.btn_arm.setStyleSheet("background-color: red;")
        self.btn_arm.setObjectName("btn_arm")
        self.stackedWidget.addWidget(self.Home)
        self.Crowdnav = QtWidgets.QWidget()
        self.Crowdnav.setStyleSheet("background: qlineargradient(\n"
"    spread:pad, x1:0, y1:0, x2:1, y2:1, \n"
"    stop:0 #ff9a9e, stop:1 #fad0c4\n"
");\n"
"color: #3A3A3A;\n"
"")
        self.Crowdnav.setObjectName("Crowdnav")
        self.label = QtWidgets.QLabel(self.Crowdnav)
        self.label.setGeometry(QtCore.QRect(70, 50, 171, 41))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label.setFont(font)
        self.label.setStyleSheet("\n"
"    background: transparent;")
        self.label.setObjectName("label")
        self.btn_home_5 = QtWidgets.QPushButton(self.Crowdnav)
        self.btn_home_5.setGeometry(QtCore.QRect(580, 450, 151, 41))
        self.btn_home_5.setStyleSheet("QPushButton {\n"
"    background: #ff7eb3;\n"
"    color: white;\n"
"    border: none;\n"
"    padding: 12px 24px;\n"
"    font-size: 16px;\n"
"    font-weight: bold;\n"
"    border-radius: 8px;\n"
"    transition: background 0.3s ease-in-out, transform 0.2s ease-in-out;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background: #ff527b;\n"
"    transform: scale(1.05);\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background: #ff305a;\n"
"    transform: scale(0.98);\n"
"}\n"
"")
        self.btn_home_5.setObjectName("btn_home_5")
        self.stackedWidget.addWidget(self.Crowdnav)
        self.Multifloor = QtWidgets.QWidget()
        self.Multifloor.setStyleSheet("background: qlineargradient(\n"
"    spread:pad, x1:0, y1:0, x2:1, y2:1, \n"
"    stop:0 #b2fefa, stop:1 #0ed2f7\n"
");\n"
"color: #333333;\n"
"")
        self.Multifloor.setObjectName("Multifloor")
        self.label_2 = QtWidgets.QLabel(self.Multifloor)
        self.label_2.setGeometry(QtCore.QRect(50, 50, 241, 41))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("\n"
"    background: transparent;")
        self.label_2.setObjectName("label_2")
        self.btn_home_4 = QtWidgets.QPushButton(self.Multifloor)
        self.btn_home_4.setGeometry(QtCore.QRect(580, 450, 151, 41))
        self.btn_home_4.setStyleSheet("QPushButton {\n"
"    background: #ff7eb3;\n"
"    color: white;\n"
"    border: none;\n"
"    padding: 12px 24px;\n"
"    font-size: 16px;\n"
"    font-weight: bold;\n"
"    border-radius: 8px;\n"
"    transition: background 0.3s ease-in-out, transform 0.2s ease-in-out;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background: #ff527b;\n"
"    transform: scale(1.05);\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background: #ff305a;\n"
"    transform: scale(0.98);\n"
"}\n"
"")
        self.btn_home_4.setObjectName("btn_home_4")
        self.stackedWidget.addWidget(self.Multifloor)
        self.Arm = QtWidgets.QWidget()
        self.Arm.setStyleSheet("background: qlineargradient(\n"
"    spread:pad, x1:0, y1:0, x2:1, y2:1, \n"
"    stop:0 #005AA7, stop:1 #00C6FB\n"
");\n"
"color: #FFFFFF;\n"
"")
        self.Arm.setObjectName("Arm")
        self.btn_home_3 = QtWidgets.QPushButton(self.Arm)
        self.btn_home_3.setGeometry(QtCore.QRect(580, 450, 151, 41))
        self.btn_home_3.setStyleSheet("QPushButton {\n"
"    background: #ff7eb3;\n"
"    color: white;\n"
"    border: none;\n"
"    padding: 12px 24px;\n"
"    font-size: 16px;\n"
"    font-weight: bold;\n"
"    border-radius: 8px;\n"
"    transition: background 0.3s ease-in-out, transform 0.2s ease-in-out;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background: #ff527b;\n"
"    transform: scale(1.05);\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background: #ff305a;\n"
"    transform: scale(0.98);\n"
"}\n"
"")
        self.btn_home_3.setObjectName("btn_home_3")
        self.label_3 = QtWidgets.QLabel(self.Arm)
        self.label_3.setGeometry(QtCore.QRect(60, 40, 241, 41))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("\n"
"    background: transparent;")
        self.label_3.setObjectName("label_3")
        self.stackedWidget.addWidget(self.Arm)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.stackedWidget.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.btn_crowdnav.setText(_translate("MainWindow", "Crowd Navigation"))
        self.btn_muiltinav.setText(_translate("MainWindow", "Multifloor Navigation"))
        self.btn_arm.setText(_translate("MainWindow", "Arm Manipulator"))
        self.label.setText(_translate("MainWindow", "Crowd Navigation"))
        self.btn_home_5.setText(_translate("MainWindow", "Home"))
        self.label_2.setText(_translate("MainWindow", "Multifloor Navigation"))
        self.btn_home_4.setText(_translate("MainWindow", "Home"))
        self.btn_home_3.setText(_translate("MainWindow", "Home"))
        self.label_3.setText(_translate("MainWindow", "Arm Manipulator"))
