# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'robot_gui_test3.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        MainWindow.setStyleSheet("/* Main Window Background */\n"
"QMainWindow {\n"
"    background-color: #F7F9FC;  /* Soft Light Background */\n"
"    color: #2E3440;\n"
"}\n"
"\n"
"/* General Widget Background */\n"
"QWidget {\n"
"    background: #FFFFFF;  \n"
"    border-radius: 10px;\n"
"}\n"
"\n"
"/* Stacked Widget */\n"
"QStackedWidget {\n"
"    background: #FFFFFF;\n"
"    border-radius: 10px;\n"
"    padding: 10px;\n"
"}\n"
"\n"
"/* Buttons */\n"
"QPushButton {\n"
"    background-color: #4A90E2;  /* Soft Blue */\n"
"    color: white;\n"
"    font-size: 16px;\n"
"    padding: 8px 12px;\n"
"    border-radius: 8px;\n"
"    border: 2px solid #357ABD;\n"
"    transition: 0.3s;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #357ABD;\n"
"    border: 2px solid #4A90E2;\n"
"}\n"
"\n"
"/* Labels */\n"
"QLabel {\n"
"    font-size: 18px;\n"
"    color: #2E3440;\n"
"    font-weight: bold;\n"
"}\n"
"\n"
"/* Line Edit (Text Input) */\n"
"QLineEdit {\n"
"    background-color: #E3EAF2;\n"
"    color: #2E3440;\n"
"    border: 1px solid #A0AEC0;\n"
"    border-radius: 5px;\n"
"    padding: 5px;\n"
"}\n"
"\n"
"/* Styled Scrollbars */\n"
"QScrollBar:vertical {\n"
"    border: none;\n"
"    background: #F1F5F9;\n"
"    width: 10px;\n"
"    margin: 0px 0px 0px 0px;\n"
"}\n"
"\n"
"QScrollBar::handle:vertical {\n"
"    background: #A0AEC0;\n"
"    min-height: 20px;\n"
"    border-radius: 5px;\n"
"}\n"
"\n"
"QScrollBar::add-line:vertical, \n"
"QScrollBar::sub-line:vertical {\n"
"    background: none;\n"
"}\n"
"\n"
"/* ComboBox */\n"
"QComboBox {\n"
"    background-color: #FFFFFF;\n"
"    border: 1px solid #A0AEC0;\n"
"    border-radius: 5px;\n"
"    padding: 5px;\n"
"}\n"
"\n"
"QComboBox::drop-down {\n"
"    border: none;\n"
"}\n"
"\n"
"QComboBox:hover {\n"
"    border: 1px solid #4A90E2;\n"
"}\n"
"")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.btn_crowdnav = QtWidgets.QPushButton(self.centralwidget)
        self.btn_crowdnav.setGeometry(QtCore.QRect(80, 520, 161, 41))
        self.btn_crowdnav.setStyleSheet("")
        self.btn_crowdnav.setObjectName("btn_crowdnav")
        self.btn_multifloor = QtWidgets.QPushButton(self.centralwidget)
        self.btn_multifloor.setGeometry(QtCore.QRect(260, 520, 211, 41))
        self.btn_multifloor.setStyleSheet("")
        self.btn_multifloor.setObjectName("btn_multifloor")
        self.btn_arm = QtWidgets.QPushButton(self.centralwidget)
        self.btn_arm.setGeometry(QtCore.QRect(490, 520, 181, 41))
        self.btn_arm.setStyleSheet("")
        self.btn_arm.setObjectName("btn_arm")
        self.mainstack = QtWidgets.QStackedWidget(self.centralwidget)
        self.mainstack.setGeometry(QtCore.QRect(59, 239, 691, 251))
        self.mainstack.setStyleSheet("")
        self.mainstack.setObjectName("mainstack")
        self.CrowdNav = QtWidgets.QWidget()
        self.CrowdNav.setObjectName("CrowdNav")
        self.btn_crwnav_run = QtWidgets.QPushButton(self.CrowdNav)
        self.btn_crwnav_run.setGeometry(QtCore.QRect(270, 80, 81, 41))
        self.btn_crwnav_run.setObjectName("btn_crwnav_run")
        self.crwnav_goal_input = QtWidgets.QTextEdit(self.CrowdNav)
        self.crwnav_goal_input.setGeometry(QtCore.QRect(30, 79, 211, 51))
        self.crwnav_goal_input.setStyleSheet("background-color: #F8F9FA;  /* Light Gray */\n"
"    color: #333333;  /* Dark Gray Text */\n"
"    font-size: 16px;\n"
"    padding: 8px;\n"
"    border: 2px solid #CCCCCC;  /* Light Border */\n"
"    border-radius: 6px;\n"
"    outline: none;")
        self.crwnav_goal_input.setObjectName("crwnav_goal_input")
        self.mainstack.addWidget(self.CrowdNav)
        self.Multifloor = QtWidgets.QWidget()
        self.Multifloor.setObjectName("Multifloor")
        self.floorStack = QtWidgets.QStackedWidget(self.Multifloor)
        self.floorStack.setGeometry(QtCore.QRect(30, 20, 611, 131))
        self.floorStack.setStyleSheet("background-color: #E3EAF2;\n"
"    color: #2E3440;\n"
"    border: 1px solid #A0AEC0;\n"
"    border-radius: 5px;\n"
"    padding: 5px;")
        self.floorStack.setObjectName("floorStack")
        self.pg_flr_G = QtWidgets.QWidget()
        self.pg_flr_G.setObjectName("pg_flr_G")
        self.btn_reception = QtWidgets.QPushButton(self.pg_flr_G)
        self.btn_reception.setGeometry(QtCore.QRect(30, 40, 89, 25))
        self.btn_reception.setObjectName("btn_reception")
        self.btn_entc1 = QtWidgets.QPushButton(self.pg_flr_G)
        self.btn_entc1.setGeometry(QtCore.QRect(200, 40, 89, 25))
        self.btn_entc1.setObjectName("btn_entc1")
        self.btn_uav = QtWidgets.QPushButton(self.pg_flr_G)
        self.btn_uav.setGeometry(QtCore.QRect(380, 40, 89, 25))
        self.btn_uav.setObjectName("btn_uav")
        self.floorStack.addWidget(self.pg_flr_G)
        self.pg_flr_1 = QtWidgets.QWidget()
        self.pg_flr_1.setObjectName("pg_flr_1")
        self.btn_com_lab = QtWidgets.QPushButton(self.pg_flr_1)
        self.btn_com_lab.setGeometry(QtCore.QRect(70, 40, 121, 25))
        self.btn_com_lab.setObjectName("btn_com_lab")
        self.btn_office = QtWidgets.QPushButton(self.pg_flr_1)
        self.btn_office.setGeometry(QtCore.QRect(230, 40, 89, 25))
        self.btn_office.setObjectName("btn_office")
        self.btn_conference = QtWidgets.QPushButton(self.pg_flr_1)
        self.btn_conference.setGeometry(QtCore.QRect(380, 40, 171, 25))
        self.btn_conference.setObjectName("btn_conference")
        self.floorStack.addWidget(self.pg_flr_1)
        self.pg_flr_2 = QtWidgets.QWidget()
        self.pg_flr_2.setObjectName("pg_flr_2")
        self.btn_digi_lab = QtWidgets.QPushButton(self.pg_flr_2)
        self.btn_digi_lab.setGeometry(QtCore.QRect(100, 60, 151, 31))
        self.btn_digi_lab.setObjectName("btn_digi_lab")
        self.btn_analog_lab = QtWidgets.QPushButton(self.pg_flr_2)
        self.btn_analog_lab.setGeometry(QtCore.QRect(290, 60, 151, 31))
        self.btn_analog_lab.setObjectName("btn_analog_lab")
        self.floorStack.addWidget(self.pg_flr_2)
        self.pg_flr_3 = QtWidgets.QWidget()
        self.pg_flr_3.setObjectName("pg_flr_3")
        self.btn_pg_room = QtWidgets.QPushButton(self.pg_flr_3)
        self.btn_pg_room.setGeometry(QtCore.QRect(70, 50, 171, 41))
        self.btn_pg_room.setObjectName("btn_pg_room")
        self.btn_tele_lab = QtWidgets.QPushButton(self.pg_flr_3)
        self.btn_tele_lab.setGeometry(QtCore.QRect(270, 50, 161, 41))
        self.btn_tele_lab.setObjectName("btn_tele_lab")
        self.floorStack.addWidget(self.pg_flr_3)
        self.btn_flr_G = QtWidgets.QPushButton(self.Multifloor)
        self.btn_flr_G.setGeometry(QtCore.QRect(50, 170, 121, 41))
        self.btn_flr_G.setStyleSheet("QPushButton {\n"
"    background-color: #B8E0D2;  /* Light Mint Green */\n"
"    color: #2E3440;\n"
"    font-size: 16px;\n"
"    padding: 8px 12px;\n"
"    border-radius: 8px;\n"
"    border: 2px solid #90C9B7;\n"
"    transition: 0.3s;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #90C9B7;\n"
"    border: 2px solid #6CA893;\n"
"}\n"
"")
        self.btn_flr_G.setObjectName("btn_flr_G")
        self.btn_flr_1 = QtWidgets.QPushButton(self.Multifloor)
        self.btn_flr_1.setGeometry(QtCore.QRect(200, 170, 131, 41))
        self.btn_flr_1.setStyleSheet("QPushButton {\n"
"    background-color: #B8E0D2;  /* Light Mint Green */\n"
"    color: #2E3440;\n"
"    font-size: 16px;\n"
"    padding: 8px 12px;\n"
"    border-radius: 8px;\n"
"    border: 2px solid #90C9B7;\n"
"    transition: 0.3s;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #90C9B7;\n"
"    border: 2px solid #6CA893;\n"
"}\n"
"")
        self.btn_flr_1.setObjectName("btn_flr_1")
        self.btn_flr_2 = QtWidgets.QPushButton(self.Multifloor)
        self.btn_flr_2.setGeometry(QtCore.QRect(360, 170, 131, 41))
        self.btn_flr_2.setStyleSheet("QPushButton {\n"
"    background-color: #B8E0D2;  /* Light Mint Green */\n"
"    color: #2E3440;\n"
"    font-size: 16px;\n"
"    padding: 8px 12px;\n"
"    border-radius: 8px;\n"
"    border: 2px solid #90C9B7;\n"
"    transition: 0.3s;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #90C9B7;\n"
"    border: 2px solid #6CA893;\n"
"}\n"
"")
        self.btn_flr_2.setObjectName("btn_flr_2")
        self.btn_flr_3 = QtWidgets.QPushButton(self.Multifloor)
        self.btn_flr_3.setGeometry(QtCore.QRect(510, 170, 131, 41))
        self.btn_flr_3.setStyleSheet("QPushButton {\n"
"    background-color: #B8E0D2;  /* Light Mint Green */\n"
"    color: #2E3440;\n"
"    font-size: 16px;\n"
"    padding: 8px 12px;\n"
"    border-radius: 8px;\n"
"    border: 2px solid #90C9B7;\n"
"    transition: 0.3s;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #90C9B7;\n"
"    border: 2px solid #6CA893;\n"
"}\n"
"")
        self.btn_flr_3.setObjectName("btn_flr_3")
        self.mainstack.addWidget(self.Multifloor)
        self.Arm = QtWidgets.QWidget()
        self.Arm.setObjectName("Arm")
        self.btn_ayubowan = QtWidgets.QPushButton(self.Arm)
        self.btn_ayubowan.setGeometry(QtCore.QRect(60, 70, 121, 51))
        self.btn_ayubowan.setStyleSheet("QPushButton {\n"
"    background-color: #B8E0D2;  /* Light Mint Green */\n"
"    color: #2E3440;\n"
"    font-size: 16px;\n"
"    padding: 8px 12px;\n"
"    border-radius: 8px;\n"
"    border: 2px solid #90C9B7;\n"
"    transition: 0.3s;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #90C9B7;\n"
"    border: 2px solid #6CA893;\n"
"}\n"
"")
        self.btn_ayubowan.setObjectName("btn_ayubowan")
        self.btn_hi = QtWidgets.QPushButton(self.Arm)
        self.btn_hi.setGeometry(QtCore.QRect(210, 70, 111, 51))
        self.btn_hi.setStyleSheet("QPushButton {\n"
"    background-color: #B8E0D2;  /* Light Mint Green */\n"
"    color: #2E3440;\n"
"    font-size: 16px;\n"
"    padding: 8px 12px;\n"
"    border-radius: 8px;\n"
"    border: 2px solid #90C9B7;\n"
"    transition: 0.3s;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #90C9B7;\n"
"    border: 2px solid #6CA893;\n"
"}\n"
"")
        self.btn_hi.setObjectName("btn_hi")
        self.btn_highfive = QtWidgets.QPushButton(self.Arm)
        self.btn_highfive.setGeometry(QtCore.QRect(350, 70, 121, 51))
        self.btn_highfive.setStyleSheet("QPushButton {\n"
"    background-color: #B8E0D2;  /* Light Mint Green */\n"
"    color: #2E3440;\n"
"    font-size: 16px;\n"
"    padding: 8px 12px;\n"
"    border-radius: 8px;\n"
"    border: 2px solid #90C9B7;\n"
"    transition: 0.3s;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #90C9B7;\n"
"    border: 2px solid #6CA893;\n"
"}\n"
"")
        self.btn_highfive.setObjectName("btn_highfive")
        self.mainstack.addWidget(self.Arm)
        self.Notifications = QtWidgets.QLabel(self.centralwidget)
        self.Notifications.setGeometry(QtCore.QRect(40, 10, 691, 151))
        font = QtGui.QFont()
        font.setFamily("Ubuntu")
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.Notifications.setFont(font)
        self.Notifications.setWordWrap(True)
        self.Notifications.setObjectName("Notifications")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(60, 196, 211, 31))
        self.label.setObjectName("label")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.floorStack.setCurrentIndex(3)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.btn_crowdnav.setText(_translate("MainWindow", "Crowd Navigation"))
        self.btn_multifloor.setText(_translate("MainWindow", "Multifloor Navigation"))
        self.btn_arm.setText(_translate("MainWindow", "Arm Manipulator"))
        self.btn_crwnav_run.setText(_translate("MainWindow", "Run"))
        self.btn_reception.setText(_translate("MainWindow", "Reception"))
        self.btn_entc1.setText(_translate("MainWindow", "ENTC1"))
        self.btn_uav.setText(_translate("MainWindow", "UAV"))
        self.btn_com_lab.setText(_translate("MainWindow", "Computer lab"))
        self.btn_office.setText(_translate("MainWindow", "Office"))
        self.btn_conference.setText(_translate("MainWindow", "Conference Room"))
        self.btn_digi_lab.setText(_translate("MainWindow", "Digitab lab"))
        self.btn_analog_lab.setText(_translate("MainWindow", "Analog Lab"))
        self.btn_pg_room.setText(_translate("MainWindow", "PG Seminar Room"))
        self.btn_tele_lab.setText(_translate("MainWindow", "Telecom Lab"))
        self.btn_flr_G.setText(_translate("MainWindow", "Ground Floor"))
        self.btn_flr_1.setText(_translate("MainWindow", "1st Floor"))
        self.btn_flr_2.setText(_translate("MainWindow", "2nd Floor"))
        self.btn_flr_3.setText(_translate("MainWindow", "3rd Floor"))
        self.btn_ayubowan.setText(_translate("MainWindow", "Ayubowan"))
        self.btn_hi.setText(_translate("MainWindow", "Hi"))
        self.btn_highfive.setText(_translate("MainWindow", "HighFive"))
        self.Notifications.setText(_translate("MainWindow", "Notifications"))
        self.label.setText(_translate("MainWindow", "Crowd Navigation"))
