# Locations : [X, Y, Theta]
# location1: [3.0, 0.0, 0.0]
# location2: [3.0, -3.0, 1.57]
# location3: [-3.0, -3.0, -0.7]
# location4: [ -3.0, 0.0, 1.57]

location1: [3.58, -2.12, 0.0]
location2: [-2.52, -0.90, 1.57]
location3: [-2.847, 2.292, -1.57]
location4: [ -5.68, -3.54, -1.57]

posegraph_file: "/home/sithija/mobile_receptionist_ws/src/smrr_localization/maps/floor05"