multinav_status:
  current_floor: 2
  desired_floor: 1
  current_floor_opened: /home/sithija/mobile_receptionist_ws/src/smrr_localization/maps/BT_floor_02_open
  current_floor_closed: /home/sithija/mobile_receptionist_ws/src/smrr_localization/maps/BT_floor_02_closed
  desired_floor_opened: /home/sithija/mobile_receptionist_ws/src/smrr_localization/maps/BT_floor_01_open
dock_station:
  floor_no: 2
  location: [-3.0, -3.0, 0.0]
elevator_locations:
  location1: [2.0, -2.12, -0.5]
  location2: [3.4, 0.0, 1.57]
  location3: [2.6, 1.5, -1.57]
  location4:
    - 8
    - -3
    - 0
preloaded_maps:
  closedMap1: /home/sithija/mobile_receptionist_ws/src/smrr_localization/maps/BT_floor_01_closed
  openedMap1: /home/sithija/mobile_receptionist_ws/src/smrr_localization/maps/BT_floor_01_open
  closedMap2: /home/sithija/mobile_receptionist_ws/src/smrr_localization/maps/BT_floor_02_closed
  openedMap2: /home/sithija/mobile_receptionist_ws/src/smrr_localization/maps/BT_floor_02_open
  closedMap3: /home/sithija/mobile_receptionist_ws/src/smrr_localization/maps/BT_floor_03_closed
  openedMap3: /home/sithija/mobile_receptionist_ws/src/smrr_localization/maps/BT_floor_03_open
rotate_to_elevator:
  K_P: 1.0
  K_D: 0.6